name: Self-hosted quick test
on: workflow_dispatch

jobs:
  ping:
    runs-on: [self-hosted, Windows, X64]
    defaults:
      run:
        shell: powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File {0}
    steps:
      - name: Runner / IP check (resilient)
        run: |
          Write-Host "Machine: $env:COMPUTERNAME"
          Write-Host "User:    $env:USERNAME"
          Write-Host "PS:      $($PSVersionTable.PSVersion)"
          try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13 } catch {}
          $ProgressPreference = 'SilentlyContinue'
          $ip4 = $null
          try { $ip4 = (Invoke-RestMethod -Uri 'https://api.ipify.org' -TimeoutSec 10 -ErrorAction Stop) } catch {}
          if (-not $ip4) { try { $ip4 = (Invoke-WebRequest -Uri 'https://api.ipify.org' -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop).Content } catch {} }
          if (-not $ip4) { try { $ip4 = (curl.exe -s https://api.ipify.org) } catch {} }
          Write-Host "Outbound IPv4: $ip4"
          exit 0
